apiVersion: v1
kind: Namespace
metadata:
  name: gabriele-stream
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jgroups-service-account
  namespace: gabriele-stream
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "jgroups-api-access-gabriele-stream"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jgroups-pod-reader
subjects:
- kind: ServiceAccount
  name: jgroups-service-account
  namespace: gabriele-stream
