apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-go-stream-client
  labels:
    app: rmq-go-stream-client
spec:
  selector:
    matchLabels:
      app: rmq-go-stream-client
  revisionHistoryLimit: 10
  replicas: 4
  template:
    metadata:
      labels:
        app: rmq-go-stream-client
    spec:
      containers:
        - name: go-stream-perf-test
          imagePullPolicy: Always
          image: pivotalrabbitmq/go-stream-perf-test
          args: ["--publishers", "1", "--consumers", "5", "--rate","1000","--uris", "rabbitmq-stream://test:test@stream-clients.gabriele.svc.cluster.local:5552/"]
         