# apiVersion: v1
# kind: Namespace
# metadata:
#   name: gabriele
# ---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: stream-test
  namespace: gabriele-stream
spec:
  replicas: 3
  image: rabbitmq:4-management
  service:
    type: LoadBalancer
  # tls:
  #   secretName: tls-secret
  resources:
    requests:
      cpu: 12
      memory: 8Gi
    limits:
      cpu: 12
      memory: 8Gi
  persistence:
    storageClassName: standard-rwo
    storage: "100Gi"
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stream
      - rabbitmq_stream_management
    additionalConfig: |
      log.console = true
      log.console.level = debug