# apiVersion: v1
# kind: Namespace
# metadata:
  # name: stream-clients-test
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: stream-clients
  namespace: performance-tests
spec:
  replicas: 3
  image: rabbitmq:4-management
  service:
    type: LoadBalancer
  # tls:
    # secretName: tls-secret
  resources:
    requests:
      cpu: 4
      memory: 3Gi
    limits:
      cpu: 4
      memory: 3Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stream
      - rabbitmq_stream_management
    additionalConfig: |
      log.console = true
      log.console.level = debug